# ======= DATASET ==============================================================
DATASET.PARSER: null
DATASET.LABELS: {}
DATASET.ANNOTATIONS_PATH: null
DATASET.IMAGES_PATH: null

# ======= VISUALIZATION PARAMETERS =============================================
# Images
VIS.IMG_WIDTH:  null
VIS.IMG_HEIGHT:  null
VIS.IMG_BACKGROUND: True
VIS.IMG_BG_COLOR: [0, 0, 0]

# Text
VIS.TEXT.VISIBLE: True
VIS.TEXT.SCALE:  1
VIS.TEXT.THICKNESS:  1
VIS.TEXT.COLOR: [255, 255, 255]
VIS.TEXT.PALETTE: null       # Seaborn color palette or list of colors
VIS.TEXT.COLOR_SOURCE: SOLID # ColorSource Enum
VIS.TEXT.LINE_SPACE: 15
VIS.TEXT.POSITION: BOTTOM_RIGHT # RelativePosition Enum

# Text background
VIS.TEXT_BG.VISIBLE: True
VIS.TEXT_BG.COLOR: [224, 56, 84]
VIS.TEXT_BG.ALPHA: 0.75
VIS.TEXT_BG.PALETTE: null       # Seaborn color palette or list of colors
VIS.TEXT_BG.COLOR_SOURCE: LABEL # ColorSource Enum
VIS.TEXT_BG.MARGIN: 5

# WARNING: This expression will be executed with an ``eval``!!
VIS.TEXT.FORMATTER: f"{instance.label} ({instance.label_id})"

# Bounding boxes
VIS.BOX.VISIBLE: True
VIS.BOX.THICKNESS:  1
VIS.BOX.COLOR: [224, 56, 84]
VIS.BOX.ALPHA: 1
VIS.BOX.PALETTE: null            # Seaborn color palette or list of colors
VIS.BOX.COLOR_SOURCE: LABEL      # ColorSource Enum
VIS.BOX.TEXT_POSITION: TOP_LEFT  # RelativePosition Enum
VIS.BOX.FILL: False

# Segmentation masks
VIS.MASK.VISIBLE: True
VIS.MASK.ALPHA: 0.75
VIS.MASK.COLOR: [21, 57, 255]
VIS.MASK.PALETTE: null       # Seaborn color palette or list of colors
VIS.MASK.COLOR_SOURCE: LABEL # ColorSource Enum

# Keypoints
VIS.KP.VISIBLE: True
VIS.KP.RADIUS:  5
VIS.KP.LINE_THICKNESS:  3
VIS.KP.NAMES_VISIBLE: False
VIS.KP.CONNECTIONS_VISIBLE: True
VIS.KP.KP_VISIBLE: True
VIS.KP.COLOR: [0, 0, 255]
VIS.KP.COLOR_SOURCE: LABEL    # ColorSource Enum
VIS.KP.KP_COLORS: {
    "left_ear": [255, 0, 255],
    "right_ear": [255, 255, 0],
    "left_eye": [223, 0, 255],
    "right_eye": [223, 255, 0],
    "nose": [255, 255, 255],
    "left_shoulder": [191, 0, 255],
    "right_shoulder": [191, 255, 0],
    "left_elbow": [159, 0, 255],
    "right_elbow": [159, 255, 0],
    "left_wrist": [127, 0, 255],
    "right_wrist": [127, 255, 0],
    "left_hip": [95, 0, 255],
    "right_hip": [95, 255, 0],
    "left_knee": [63, 0, 255],
    "right_knee": [63, 255, 0],
    "left_ankle": [31, 0, 255],
    "right_ankle": [31, 255, 0]
}
VIS.KP.CONNECTIONS:
    - ["left_ear", "left_eye", [239, 0, 255]]
    - ["right_ear", "right_eye", [239, 235, 0]]
    - ["left_eye", "nose", [255, 0, 255]]
    - ["nose", "right_eye", [255, 255, 0]]
    - ["left_shoulder", "right_shoulder", [191, 255, 255]]
    - ["left_shoulder", "left_elbow", [175, 0, 255]]
    - ["right_shoulder", "right_elbow", [175, 255, 0]]
    - ["left_elbow", "left_wrist", [143, 0, 255]]
    - ["right_elbow", "right_wrist", [143, 255, 0]]
    - ["left_hip", "right_hip", [95, 255, 255]]
    - ["left_hip", "left_knee", [63, 0, 255]]
    - ["right_hip", "right_knee", [63, 255, 0]]
    - ["left_knee", "left_ankle", [47, 0, 255]]
    - ["right_knee", "right_ankle", [47, 255, 0]]
    - ["left_shoulder", "left_hip", [143, 0, 255]]
    - ["right_shoulder", "right_hip", [143, 255, 0]]
    - ["nose", "left_shoulder", [223, 0, 255]]
    - ["nose", "right_shoulder", [223, 255, 0]]
